# Generated by Django 2.2 on 2022-11-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220919_1327'),
        ('shop', '0003_alter_categ_options'),
    ]

    operations = [
    ]
