# Generated by Django 2.2 on 2022-11-03 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20221102_1511'),
        ('shop', '0006_products_available'),
    ]

    operations = [
    ]
