# Generated by Django 2.2 on 2022-11-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20221108_1051'),
        ('shop', '0007_merge_20221103_1355'),
    ]

    operations = [
    ]
