# Generated by Django 2.2 on 2022-11-02 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_items_active'),
        ('cart', '0003_auto_20221102_1247'),
    ]

    operations = [
    ]
